apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Values.namespace | default "conference" }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
# Explication: Secret pour creds sensibles (base64 encodé). Valeurs injectées depuis values.yaml. Jamais committer en clair (sécurité, ch.2). Utilisé par EnvFrom dans deployments.