apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Values.namespace | default "conference" }}
spec:
  type: {{ .Values.frontend.service.type | default "ClusterIP" }}
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
# Explication: Service pour discovery du frontend. Type ClusterIP par défaut, exposable via Ingress (ch.3 pour platform APIs).