apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notifications
  namespace: {{ .Values.namespace | default "conference" }}
spec:
  type: ClusterIP
  selector:
    app: notifications
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
# Explication: Service interne pour notifications-service.